/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace Microfinance {
  export type LoanStruct = {
    borrower: AddressLike;
    amount: BigNumberish;
    duration: BigNumberish;
    purpose: string;
    status: BigNumberish;
    dueDate: BigNumberish;
    lender: AddressLike;
  };

  export type LoanStructOutput = [
    borrower: string,
    amount: bigint,
    duration: bigint,
    purpose: string,
    status: bigint,
    dueDate: bigint,
    lender: string
  ] & {
    borrower: string;
    amount: bigint;
    duration: bigint;
    purpose: string;
    status: bigint;
    dueDate: bigint;
    lender: string;
  };
}

export interface MicrofinanceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "approveLoan"
      | "borrowerFeeBps"
      | "creditScores"
      | "fundLoan"
      | "getLoan"
      | "getLoanCount"
      | "getUserCreditScore"
      | "getUserLoanAtIndex"
      | "getUserLoanCount"
      | "lenderFeeBps"
      | "loans"
      | "owner"
      | "pause"
      | "paused"
      | "rejectLoan"
      | "renounceOwnership"
      | "repayLoan"
      | "requestLoan"
      | "setFees"
      | "setTreasury"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "userLoans"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LoanFunded"
      | "LoanRejected"
      | "LoanRepaid"
      | "LoanRequested"
      | "OwnershipTransferred"
      | "Paused"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "approveLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowerFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "creditScores",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fundLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoanCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCreditScore",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLoanAtIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLoanCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lenderFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rejectLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setFees",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userLoans",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borrowerFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLoanCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserCreditScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLoanAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLoanCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lenderFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rejectLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setFees", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userLoans", data: BytesLike): Result;
}

export namespace LoanFundedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    lender: AddressLike,
    amount: BigNumberish,
    lenderFee: BigNumberish,
    borrowerFee: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    lender: string,
    amount: bigint,
    lenderFee: bigint,
    borrowerFee: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    lender: string;
    amount: bigint;
    lenderFee: bigint;
    borrowerFee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRejectedEvent {
  export type InputTuple = [loanId: BigNumberish, borrower: AddressLike];
  export type OutputTuple = [loanId: bigint, borrower: string];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    lender: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    lender: string,
    amount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    lender: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRequestedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    amount: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    amount: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Microfinance extends BaseContract {
  connect(runner?: ContractRunner | null): Microfinance;
  waitForDeployment(): Promise<this>;

  interface: MicrofinanceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  approveLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  borrowerFeeBps: TypedContractMethod<[], [bigint], "view">;

  creditScores: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  fundLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;

  getLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [
      [string, bigint, bigint, string, bigint, bigint, string] & {
        borrower: string;
        amount: bigint;
        duration: bigint;
        purpose: string;
        status: bigint;
        dueDate: bigint;
        lender: string;
      }
    ],
    "view"
  >;

  getLoanCount: TypedContractMethod<[], [bigint], "view">;

  getUserCreditScore: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getUserLoanAtIndex: TypedContractMethod<
    [_user: AddressLike, _index: BigNumberish],
    [Microfinance.LoanStructOutput],
    "view"
  >;

  getUserLoanCount: TypedContractMethod<[_user: AddressLike], [bigint], "view">;

  lenderFeeBps: TypedContractMethod<[], [bigint], "view">;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string, bigint, bigint, string] & {
        borrower: string;
        amount: bigint;
        duration: bigint;
        purpose: string;
        status: bigint;
        dueDate: bigint;
        lender: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  rejectLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;

  requestLoan: TypedContractMethod<
    [_amount: BigNumberish, _duration: BigNumberish, _purpose: string],
    [bigint],
    "nonpayable"
  >;

  setFees: TypedContractMethod<
    [_lenderFeeBps: BigNumberish, _borrowerFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "approveLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "borrowerFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "creditScores"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [_loanId: BigNumberish],
    [
      [string, bigint, bigint, string, bigint, bigint, string] & {
        borrower: string;
        amount: bigint;
        duration: bigint;
        purpose: string;
        status: bigint;
        dueDate: bigint;
        lender: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLoanCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserCreditScore"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserLoanAtIndex"
  ): TypedContractMethod<
    [_user: AddressLike, _index: BigNumberish],
    [Microfinance.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserLoanCount"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lenderFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string, bigint, bigint, string] & {
        borrower: string;
        amount: bigint;
        duration: bigint;
        purpose: string;
        status: bigint;
        dueDate: bigint;
        lender: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "rejectLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<
    [_amount: BigNumberish, _duration: BigNumberish, _purpose: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setFees"
  ): TypedContractMethod<
    [_lenderFeeBps: BigNumberish, _borrowerFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "LoanFunded"
  ): TypedContractEvent<
    LoanFundedEvent.InputTuple,
    LoanFundedEvent.OutputTuple,
    LoanFundedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRejected"
  ): TypedContractEvent<
    LoanRejectedEvent.InputTuple,
    LoanRejectedEvent.OutputTuple,
    LoanRejectedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanRequested"
  ): TypedContractEvent<
    LoanRequestedEvent.InputTuple,
    LoanRequestedEvent.OutputTuple,
    LoanRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "LoanFunded(uint256,address,address,uint256,uint256,uint256)": TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;
    LoanFunded: TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;

    "LoanRejected(uint256,address)": TypedContractEvent<
      LoanRejectedEvent.InputTuple,
      LoanRejectedEvent.OutputTuple,
      LoanRejectedEvent.OutputObject
    >;
    LoanRejected: TypedContractEvent<
      LoanRejectedEvent.InputTuple,
      LoanRejectedEvent.OutputTuple,
      LoanRejectedEvent.OutputObject
    >;

    "LoanRepaid(uint256,address,address,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanRequested(uint256,address,uint256,uint256)": TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
    LoanRequested: TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
